# Theano - Introduction

#### About 

Theano is a Python library that allows you to define, optimize, and evaluate **mathematical expressions** involving multi-dimensional arrays efficiently. 


#### Features:
* tight integration with NumPy – Use numpy.ndarray in Theano-compiled functions.
* transparent use of a GPU – Perform data-intensive calculations up to 140x faster than with CPU.(float32 only)
* efficient symbolic differentiation – Theano does your derivatives for function with one or many inputs.
* speed and stability optimizations – Get the right answer for log(1+x) even when x is really tiny.
* dynamic C code generation – Evaluate expressions faster.
* extensive unit-testing and self-verification – Detect and diagnose many types of errors.


#### Resources

1. Website - http://deeplearning.net/software/theano/

#### Examples

* Building a simple model with Theano - Scalars
* Building a simple model with Theano - Matrices
* Building a simple model with Theano - Linear Equation

In [74]:
# #Python Import Libraries
import os
import numpy as np
import scipy as sp

In [75]:
# #Python - Import Theano
import theano
from theano import tensor as T

#### Building a simple model with Theano - Scalars

In [76]:
# #Produhttp://localhost:8888/notebooks/Theano_Tutorials/01_Introduction.ipynb#Building-a-simple-model-with-Theano---Scalarsct of two numbers

# #Theano - Symbolic Variable Initialization
# #In Theano all symbols are typed.
num_1 = T.dscalar()
num_2 = T.dscalar()

# #Theano - Model
num_product = num_1*num_2

# #Theano - Symbolic Math-> Python Function
product_function = theano.function(inputs=[num_1, num_2], outputs=num_product)

In [77]:
product_function(1,2)

array(2.0)

In [78]:
product_function(2,44)

array(88.0)

In [79]:
product_function(15.0, 22)

array(330.0)

In [80]:
product_function(product_function(15.0, 22), 11)

array(3630.0)

In [81]:
# #Instances of the TensorVariable
type(num_1)

theano.tensor.var.TensorVariable

In [82]:
num_1.type

TensorType(float64, scalar)

In [83]:
type(num_product)

theano.tensor.var.TensorVariable

In [84]:
type(product_function)

theano.compile.function_module.Function

#### Building a simple model with Theano - Matrices

In [85]:
# #Matrix Addition

# #Symbolic Matrices
mat_1 = T.dmatrix("mat_1")
mat_2 = T.dmatrix("mat_2")

# #Equation
mat_sum = mat_1 + mat_2

mat_sum_function = theano.function(inputs=[mat_1, mat_2], outputs=mat_sum)

In [86]:
# 1 2  + 10 20 = 11 22
# 3 4    30 40   33 44

mat_sum_function([[1,2], [3,4]],
                [[10, 20], [30, 40]])

array([[ 11.,  22.],
       [ 33.,  44.]])

#### Building a simple model with Theano - Linear Equation

In [87]:
# #Symbolic Vector
vec_x = T.vector("vec_x")

# #Equation
output_vec_x = vec_x + (vec_x*10)

output_vector_function = theano.function(inputs=[vec_x], outputs=output_vec_x)

In [88]:
output_vector_function([10])

array([ 110.])

In [89]:
output_vector_function([11])

array([ 121.])

In [90]:
output_vector_function([5, 10, 11])

array([  55.,  110.,  121.])