# Dive into Deep Learning - Linear Algebra & Automatic Differentiation

In [1]:
# #Import Libraries
import mxnet as mx
from mxnet import nd

c:\users\karti\appdata\local\programs\python\python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = 2
x = nd.ones(3)
y = nd.array([5,5,5])
a, x, y

(2, 
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>, 
 [5. 5. 5.]
 <NDArray 3 @cpu(0)>)

In [3]:
a*x + y


[7. 7. 7.]
<NDArray 3 @cpu(0)>

### Dot Product

In [4]:
nd.dot(x,y)


[15.]
<NDArray 1 @cpu(0)>

### Norm

In [5]:
# #l2 norm
x = nd.arange(1,5)
nd.norm(x)


[5.477226]
<NDArray 1 @cpu(0)>

In [9]:
# #l1 norm
nd.sum(nd.abs(x))


[10.]
<NDArray 1 @cpu(0)>

### Automatic Differentiation

In [10]:
from mxnet import autograd

In [26]:
x = nd.arange(1,5).reshape(4,1)
print(x)
x.attach_grad()

with autograd.record():
    y = 2*nd.dot(x.T, x) # #Explicitly building the computational graph
print(y)


[[1.]
 [2.]
 [3.]
 [4.]]
<NDArray 4x1 @cpu(0)>

[[60.]]
<NDArray 1x1 @cpu(0)>


In [27]:
y.backward() # #Gradient computation

In [30]:
y


[[60.]]
<NDArray 1x1 @cpu(0)>

In [33]:
# #y = 2*x.T*x = 2*(x**2)
# #gradient == 4*x
x, x.grad

(
 [[1.]
  [2.]
  [3.]
  [4.]]
 <NDArray 4x1 @cpu(0)>, 
 [[ 4.]
  [ 8.]
  [12.]
  [16.]]
 <NDArray 4x1 @cpu(0)>)